### DISCUSSION TITLE
Data-access storage configuration - `global.storage.data`

### DISCUSSION THREAD

**Discussion by rconway** [EOEPCA/eoepca#78] [Data Access]
Confusion exists as to the purpose of the data-access config...
```yaml
global:
  storage:
    data:
```

Does this need to point at somewhere that already contains data, or does it need to point to somewhere where data can be stored?
